export const AUTHENTICATED = "AUTHENTICATED";
export const LOGOUT = "LOGOUT";
export const CHANGE_DISPLAY_NAME = "CHANGE_DISPLAY_NAME";

export const FIREBASE_CONNECTED = "FIREBASE_CONNECTED";
export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_DISCONNECTED = "SOCKET_DISCONNECTED";

export const LOBBY_JOINED = "LOBBY_JOINED";
export const LOBBY_LEFT = "LOBBY_LEFT";